<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>JS中的error</title>
</head>
<body>
  <script>
    /*
    进一步理解JS中的错误(Error)和错误处理

      1、错误类型：
        Error：所有错误的父类型
        ReferenceError：引用的变量不存在
        TypeError：数据类型不正确
        RangeError：数据值不在其所允许的范围内
        SyntaxError：语法错误
      2、错误处理
        捕获错误：try()catch(){}
        抛出错误：throw error
      3、错误对象
        message属性：错误相关信息
        stack属性：记录信息
     */

    //演示：ReferenceError：引用的变量不存在
    // console.log(a);

    //演示：TypeError：数据类型不正确
    // const demo = () => {
    // }
    // demo()()

    //演示：RangeError：数据值不在其所允许的范围内
    // const demo = ()=>{demo()}
    // demo()

    //演示：SyntaxError：语法错误
    // console.log(2

    //如何捕获一个错误
    /*
      1、try中放可能出现错误的代码，一旦出现错误立即停止try中的代码执行，调用catch，并携带错误信息
     */
    // try{
    //   console.log(1);
    //   console.log(a);
    //   console.log(3);
    // }catch(error){
    //   console.log("catch");
    //   console.log(error);
    // }

    //如何抛出一个错误
    function demo() {
      const date = Date.now()
      if (date % 2 === 0) {
        console.log("偶数，可以正常工作");
      } else {
        throw new Error('奇数不可以工作！')
      }
    }
    try{
      demo()
    }catch(error){
      // debugger;
      console.log(error);
    }
  </script>
</body>
</html>